### ISSUE TITLE
Deepnest won't start with ubuntu 22.04

### ISSUE THREAD

**Issue by thierry7100** [deepnest-io/Deepnest#103]
The AppImage won't start properly, first time it proposes to integrate the software in the system. This is working fine. But software won't start. When launched from terminal, I got a segmentation fault message

**To Reproduce**
1. launch a terminal.
2. Goto  the folder with Deepnest
3. Launch Deepnest from terminal : ~/Applications/Deepnest-1.0.5-linux$ ./Deepnest-1.0.5-x86_64.AppImage 

**Expected behavior**
Software start

**Screenshots**
thierry@thierry-UX410UAR:~/Applications/Deepnest-1.0.5-linux$ ./Deepnest-1.0.5-x86_64.AppImage 
Segmentation error (core dumped)

**Desktop (please complete the following information):**
 - Ubuntu 22.04 (without Wayland if it helps)
 
**Additional context**

**Comment by concifederico** [comment]
Same here, however the 1.05 version AppImage source has another git --> https://github.com/Jack000/Deepnest
There is no AppImage of this fork yet, maintainer claims this is not a priority.
Regards,

Federico

**Comment by abebeos** [comment]
Hi there. This fork here was not yet enabled on linux, only windows was verified, see packages.

**Comment by abebeos** [comment]
should work with https://github.com/deepnest-io/Deepnest/releases/tag/v1.1.6
