### ISSUE TITLE
Importing Not Working

### ISSUE THREAD

**Issue by Eric142-ai** [deepnest-io/Deepnest#157]
Hello,

I've been using Deepnest for the past week to nest and it has been working as intended. This morning, I proceeded to import files as normal but none of the shapes have been registered by the import (they do not appear). I've tried previous files that have worked in the past and those haven't imported either.
Double checked if they were simply invisible by adding a sheet to nest on - no shapes, just the sheet.
Restarted PC, checked latest update version, didn't work.

Tl;dr There seems to be a problem with the importing, at least on my end.
Edit: It's dxf file type that doesnt seem to be working, it can register SVG files fine

Expected:
- Files to import and for the shapes to appear

**Screenshots**
![Screenshot 2024-11-25 105627](https://github.com/user-attachments/assets/2d6e6daf-e54d-4889-a5ca-46b93804b8f8)
![image](https://github.com/user-attachments/assets/f585f0f0-67d8-40e0-9448-1fe11d7dde99)
![image](https://github.com/user-attachments/assets/9f17afc8-201e-4884-85fb-36ff0f12ffa0)

^Checked if shapes were present by nesting on an added sheet

Desktop: 
- Windows 11 Pro
- Version: 23H2
- Browser: Microsoft Edge
- Deepnest: Both v1.0.5 (what I was using before) and v1.2.0 (what I tried after looking at latest update), both don't work.

**Comment by abebeos** [comment]
> maybe that went offline.

There was a paywall added, documented within https://deepnest.io/, but seems it is removed now.

@Eric142-ai , @fluxor99232 , is this still happening?

**Comment by Eric142-ai** [comment]
Hi both,

Thank you for the info/input. The dxf importing is working again so the issue seems to be resolved.
