### ISSUE TITLE
Consider restoring electron-settings

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#189]
electron-settings was replaced with api compatible on-the-fly code within:

* https://github.com/deepnest-io/Deepnest/pull/188

A possible patch to keep `electron-settings` is mentioned here:

* https://github.com/deepnest-io/Deepnest/pull/166#discussion_r1878004652

### Process

* Restore the original code exactly(!) (one commit)
  *  https://github.com/deepnest-io/Deepnest/compare/master...i189
* Confirm that there are problems
  * if yes: add the relevant code modifications in an 2nd commit
    * Problem:
    * Issue: https://github.com/nathanbuchar/electron-settings/issues/133#issuecomment-1372970997
      * electron-settings feels a bit unmaintained
      * request module seems to be a security risk

### Consideration

It is possibly more secure to just test the new code manually, and ideally add some automated tests that verify that different setting-types go through correctly (text, num etc.). Unit test initially, ideally e2e test.

**Comment by abebeos** [comment]
@Dexus , what was this `electron-settings.patch` about, and where did you get it? didn't find anything quickly.

**Comment by Dexus** [comment]
Need patch-package installed with script install.
Then the patch placed into patch directory. It's injecting the @electron/remote package because its not in the v4 and v5 never released which should fix it.

Send from 🛋️

**Comment by abebeos** [comment]
did you create the patch yourself? I cannot find it, and it's gone from the PR.

**Comment by Dexus** [comment]
yepp, I created it my self.

**Comment by abebeos** [comment]
electron-settings should work, without patching. Seems there's no documentation about any incompatibility.

**Comment by Dexus** [comment]
Since the `const {remote} = require('electron');` does not export `remote` anymore, you need `@electron/remote` package to have the same features. I did also not found a direct changelog that this was removes as breaking change but it was done somehow and somewhere...

**Comment by Dexus** [comment]
If you want to cheey-pick: SHA:16926e6b0f205f1eca0a7e1bccab24bcb828c1ac

**Comment by abebeos** [comment]
this sha seems to be the wrong one (https://github.com/deepnest-io/Deepnest/pull/167/commits/16926e6b0f205f1eca0a7e1bccab24bcb828c1ac) but does not matter anyways.

I've updated the issue text with a conclusion/consideration, looks like we should drop `electron-settings`, what do you think?

**Comment by Dexus** [comment]
https://github.com/deepnest-io/Deepnest/blob/16926e6b0f205f1eca0a7e1bccab24bcb828c1ac/patches/electron-settings.patch

**Comment by abebeos** [comment]
getting messy, cannot get the patch to work. Closing for now as `wontfix`, as electron-settings is quasi-unmaintained.

**Comment by Dexus** [comment]
Everything that lies outside your comfort zone is too much for you?  Oha

**Comment by abebeos** [comment]
Josef, hammse Dir ins Gehirn geschissen order watt?

Please have more precision if you feel the need to off-topic babble.

tried your patch out of curiosity. Main point is

>  electron-settings is quasi-unmaintained.

As for confort-zone:

Yes, diffs like this are far out of my comfort-zone:

https://github.com/deepnest-io/Deepnest/compare/16926e6b0f205f1eca0a7e1bccab24bcb828c1ac..b7f5c2b6be1e340df53468e336a962d8a255bba2

comfort-zone: cherry-pickable commit.

**Comment by Dexus** [comment]
It was meant as a joke. But well, you couldn't read it that way. 

I'll just withdraw so that you don't have to read any off-topic drivel.

**Comment by abebeos** [comment]
> It was meant as a joke.

My reply as well (combined with real stuff)
