### ISSUE TITLE
Replace `request` module

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#190]
avoid code-changes, try to use a drop-in replacement for now.

Candidate:

* https://www.npmjs.com/package/@root/request

## Fallback / Future

* axios
* https://github.com/deepnest-io/Deepnest/pull/183

Please state rationales (e.g.: has axios become a quasi-standard within the node domain? )

**Comment by Dexus** [comment]
Or use https://www.electronjs.org/docs/latest/api/net
