### ISSUE TITLE
Assess Quality of uriilychak/SVGnest

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#191]
https://github.com/yuriilychak/SVGnest

* How is the code-quality?
* Is it possible that focusing on this project would have less effort?
  * Or maybe just integrate the updated/bug-fixed nesting-engine to Deepnest ?

**Comment by Dexus** [comment]
Create a python -m http.server in the directory

**Comment by abebeos** [comment]
oh my... used the `npm http-server`. Anyways, closing.
