### ISSUE TITLE
Do you plan a binary release for windows?

### ISSUE THREAD

**Issue by suchja** [deepnest-io/Deepnest#22]
Actually I'm not using this project, but try to get it running for another user. Do you plan to create a binary release of deepnest? In that case I probably could stop my investigation and we simply wait for the binary release.

**Comment by abebeos** [comment]
it works now, see
- https://github.com/deepnest-io/Deepnest/issues/21#issuecomment-1534730830
- https://github.com/deepnest-io/Deepnest/issues/23

**Comment by abebeos** [comment]
> Do you plan to create a binary release of deepnest?

- #31
