### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#30]
### Status

MIT license is in root

### Expected

All different licenses are mentioned:

* https://github.com/search?q=repo%3AJack000%2FDeepnest%20license&type=code

### Process

 * Lookup the licenses within the original(!) project
 * validate any license-related commit within the new repo
   * revert if necessary
     *   #39
     *  9a8b0cac6acbdf11403d96cfb1088741419bb54a
 * [9154edd](https://github.com/deepnest-io/Deepnest/commit/9154eddc93a8dd6aa05abd0b5682bb5fb7420a5c)
 * 4c8845f65bba155103ce43ece9fc7d59f165b4cf
 * fe05102fe76cc7fc8c41ff46a52cb690f6db59e6
### Result

* A general license file in root (most possibly: MIT)
* an additional LICENSES.md file in root, listing all folders/files that have different licenses
  * mention the licenses with a link

**Comment by sashadev-sky** [comment]
@abebeos just realized you already have begun work for this group of tasks. Feel free to use my branch

**Comment by abebeos** [comment]
All good. Like many other tasks, this is an incremental process, and initially it's really just about validating what exists. I've updated the issue-text a little bit.
