### ISSUE TITLE
Bountysource

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#36]

**Comment by abebeos** [comment]
And remember to process bounties fast, thus you don't block the flow of an active developer:

https://app.bountysource.com/issues/120217906-building-with-vs2022-under-windows-11

**Comment by abebeos** [comment]
@dorkmo & others , really bad weather here, so I could speed things up even more (possibly I'll manage a release even today)

**Comment by bosd** [comment]
FYI, I wanted to back the project a bit on bounty source.. 
Did several attempts, but keep running into paypal problems on their website..

**Comment by abebeos** [comment]
bountysource is a small hell, quite bad UX/DX.

I sent you an invite to a private repo of mine.

**Comment by abebeos** [comment]
(we can handle bounties additionally directly between us, can be paypal, skrill (prefered) or crypto. No need for mediators. bounties are good to get new devs, once you have them, the overhead is annoying, the fees&delays unnecessary)

**Comment by abebeos** [comment]
Faster. folks, you need to be faster. Once I loose flow (and interest), no bounty amount can bring me back.

I'll try to process

https://github.com/deepnest-io/Deepnest/issues/24

next, though merging functionality from other repos should have priority.

But my main problem is: I do not get enough feedback re budgets. I need to know your budget-limits, so I can try to limit the scope of my work.

**Comment by abebeos** [comment]
follow-up:
- https://github.com/deepnest-io/Deepnest/discussions/20
