### ISSUE TITLE
[FEEDBACK] I need Test Data Files

### ISSUE THREAD

**Issue by abebeos** [deepnest-io/Deepnest#61]
I need some simple medium sized files in order to run tests.

**Comment by dorkmo** [comment]
heres some stuff i've worked with, mostly rectangular though, so maybe might need some other examples with curves
https://github.com/OpenSourceEcology/CEB-Press/tree/master/v1708P/xport2023

**Comment by abebeos** [comment]
> mostly rectangular though

All good, this is mostly about testing the electron/js upgrade stuff.

The important thing is that those are validated with Deepnest, as I've currently problems: 

- #65

**Comment by abebeos** [comment]
I've used the SVG files included in the distribution https://deepnest.io/#download.

The nesting works with the updated versions (I have reached node 14).

### Important

I am new to this software. I do not know:

- what currently works
- what does not work

So, possibly this should be documented clearly, e.g. like:

* importing DXF does not work
* importing SVG works
* etc.

**Comment by abebeos** [comment]
I have produced such data by simply exporting a dxf file with the original `1.0.5` version.

This DXF can be imported into our updated version `1.1.1`, so all is good, no regressions.
